Infinite.MVC5.Test/Models/ApplicationDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;

namespace Infinite.MVC5.Test.Models
{
    public class ApplicationDbContext :DbContext
    {
        public ApplicationDbContext() : base("FruitCon")
        {

        }
        public DbSet<Fruits> Fruit { get; set; }
        public DbSet<PackSize> Packs { get; set; }
        public DbSet<Category> categories { get; set; }
    }
}

Infinite.MVC5.Test/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Infinite.MVC5.Test.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string categoryName { get; set; } 
    }
}

Infinite.MVC5.Test/Models/Fruits.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Infinite.MVC5.Test.Models
{
    public class Fruits
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public int Price { get; set; }
        public int PackSizeId { get; set; }
        public int Quantity { get; set; }
        public float Discount { get; set; }
        public int TotalPrice { get; set; }
        public int CategoryId { get; set; }
        public PackSize PackSizeName { get; set; }
        public Category CategoryName { get; set; }

    }
}

Infinite.MVC5.Test/Models/PackSize.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Infinite.MVC5.Test.Models
{
    public class PackSize
    {
        public int Id { get; set; }
        public int PackSizeName { get; set; }
    }
}

Infinite.MVC5.Test/Controllers/FruitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Infinite.MVC5.Test.Models;
using System.Data.Entity;

namespace Infinite.MVC5.Test.Controllers
{
    public class FruitsController : Controller
    {
        private readonly ApplicationDbContext _context = null;

         public FruitsController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Fruits
        public ActionResult Index()
        {
            var fruits = _context.Fruit.ToList();
            return View(fruits);
        }
        public ActionResult Details(int id)
        {
            var product = _context.Fruit.Include(c => c.CategoryName).Include(s=>s.PackSizeName).FirstOrDefault(p => p.Id == id);
            if (product!= null)
            {
                return View(product);

            }
            return HttpNotFound();


        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var product = _context.Fruit.FirstOrDefault(p => p.Id == id);
            if(product != null)
            {
                var packs = _context.Packs.ToList();
                ViewBag.Packs = packs;
                //return View(product);

                var categories = _context.categories.ToList();
                ViewBag.categories = categories;
                return View(product);
            }
            return HttpNotFound("Index");
        }
        [HttpPost]
        public ActionResult Edit(Fruits fruits)
        {
            if (fruits != null)
            {
                var fruitInDb = _context.Fruit.Find(fruits.Id);
                if (fruitInDb != null)
                {
                    fruitInDb.Id = fruits.Id;
                    fruitInDb.ProductName = fruits.ProductName;
                    fruitInDb.Price = fruits.Price;
                    fruitInDb.PackSizeId = fruits.PackSizeId;
                    fruitInDb.Quantity = fruits.Quantity;
                    fruitInDb.Discount = fruits.Discount;
                    fruitInDb.TotalPrice = fruits.TotalPrice;
                    fruitInDb.CategoryId = fruits.CategoryId;
                    _context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            var Categories = _context.categories.ToList();
            ViewBag.Categories = Categories;
            return View(fruits);
        }
        




    }
}

Infinite.MVC5.Test/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Infinite.MVC5.Test.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Infinite.MVC5.Test/Views/Fruits/Details.cshtml
@using Infinite.MVC5.Test.Models;
@model Fruits
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<hr />
@*<ul>
     <li>@Model.Id<li>[dbo].[PackSizes]
     <li>@Model.productName</li>
     <li>@Model.Price</li>
     <li>@Model.Size</li>
     <li>@Model.Quantity</li>
     <li>@Model.Discount</li>
     <li>@Model.TotalPrice</li>
     <li>@Model.Category</Id>
    </ul>*@
<div class="row">
    <div class="col-md-3">
        <ul class="list-group">
            <li class="list-group-item"><b>product Id :</b>@Model.Id</li>
            <li class="list-group-item"><b>product Name :</b>@Model.ProductName</li>
            <li class="list-group-item"><b>price :</b>@Model.Price</li>
            <li class="list-group-item"><b>Quantity :</b>@Model.Quantity</li>
            <li class="list-group-item"><b>Size :</b>@Model.PackSizeName.PackSizeName</li>
            <li class="list-group-item"><b>Discount :</b>@Model.Discount</li>
            <li class="list-group-item"><b>TotalPrice :</b>@Model.TotalPrice</li>
            <li class="list-group-item"><b>CategoryId :</b>@Model.CategoryId</li>
            <li class="list-group-item"><b>CategoryName :</b>@Model.CategoryName.categoryName</li>
        </ul>


    </div>
</div>
<div class="row">
    <div class="col-md-3">
        @Html.ActionLink("Back to Index", "Index", "Fruits");
    </div>
</div>

Infinite.MVC5.Test/Views/Fruits/Edit.cshtml
@using Infinite.MVC5.Test.Models
@model Fruits
@{
    ViewBag.Title = "Edit";
}



<h2>Edit Fruits</h2>
<hr />

@using (Html.BeginForm())
{
    <div class="mb-2">
        @Html.LabelFor(p => p.Id, new { @class = "form-label" })
        @Html.TextBoxFor(p => p.Id, new { @class = "form-control" })
        @*@Html.ValidationMessageFor(p => p.Id)*@
    </div>
    <div class="mb-2">
        @Html.LabelFor(p => p.ProductName, new { @class = "form-label" })
        @Html.TextBoxFor(p => p.ProductName, new { @class = "form-control" })
        @*@Html.ValidationMessageFor(p => p.ProductName)*@
    </div>
    <div class="mb-2">
        @Html.LabelFor(p => p.Price, new { @class = "form-label" })
        @Html.TextBoxFor(p => p.Price, new { @class = "form-control" })
        @*@Html.ValidationMessageFor(p => p.Price)*@
    </div>
    <div class="mb-2">
        @Html.LabelFor(p => p.PackSizeId, new { @class = "form-label" })

        @Html.DropDownListFor(p => p.PackSizeId, new SelectList(ViewBag.Packs, "Id", "PackSizeName"), "--Select--", new { @class = "form-select" })
        @*@Html.ValidationMessageFor(p => p.PackSizeId)*@
    </div>
    <div class="mb-2">
        @Html.LabelFor(p => p.Quantity, new { @class = "form-label" })
        @Html.TextBoxFor(p => p.Quantity, new { @class = "form-control" })
        @*@Html.ValidationMessageFor(p => p.Quantity)*@
    </div>
    <div class="mb-2">
        @Html.LabelFor(p => p.Discount, new { @class = "form-label" })
        @Html.TextBoxFor(p => p.Discount, new { @class = "form-control" })
        @*@Html.ValidationMessageFor(p => p.Discount)*@
    </div>
    <div class="mb-2">
        @Html.LabelFor(p => p.TotalPrice, new { @class = "form-label" })
        @Html.TextBoxFor(p => p.TotalPrice, new { @class = "form-control" })
        @*@Html.ValidationMessageFor(p => p.TotalPrice)*@
    </div>
    <div class="mb-2">
        @Html.LabelFor(p => p.CategoryId, new { @class = "form-label" })
        @Html.DropDownListFor(p => p.CategoryId, new SelectList(ViewBag.categories, "Id", "CategoryName"), "--Select--", new { @class = "form-select" })

        @Html.ValidationMessageFor(p => p.CategoryId)
    </div>

    <div class="mt-2">
        <input type="submit" id="btnsubmit" class="btn btn-primary" value="Update" />
    </div>
}

Infinite.MVC5.Test/Views/Fruits/Index.cshtml
@model List<Infinite.MVC5.Test.Models.Fruits>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h2>List Of Fruits</h2>

<table class="table">
    <tr>
        <th>Id</th>
        <th>ProductName</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach (var prd in Model)
    {
       <tr>
           <td>@prd.Id</td>

           <td>@Html.ActionLink(prd.ProductName,"Details","Fruits", new { id = prd.Id }, null)</td>
           <td>@Html.ActionLink("Edit","Edit","Fruits",new { id = prd.Id },new {@Class = "btn btn-info" })</td>
           <td>
               @using (Html.BeginForm("Delete", "Movies", new { id = prd.Id }, FormMethod.Post))
                {
                   <button type="submit" class="btn btn-danger">Delete</button>
                }

           </td>


            
       </tr>
    }
</table>

Infinite.MVC5.Test/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Infinite.MVC5.Test/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Infinite.MVC5.Test/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Fruit Shop</h1>
    <p class="lead">Seasonal Fruits and all types of fruits available.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Fruits</h2>
        <p>
          All types of fruits are available in our store


        </p>
        <img src="https://images.pexels.com/photos/2487443/pexels-photo-2487443.jpeg?cs=srgb&dl=pexels-matheus-cenali-2487443.jpg&fm=jpg" width="100"/>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Vegetables</h2>
        <p>All types of vegetables are available in our store</p>
        <img src=""
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Infinite.MVC5.Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Fruits shop</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Online Fruit shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Index", "Index", "Fruits")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>